import * as React from 'react';
import McsIcon, { McsIconType } from '../McsIcon';

const typeList: McsIconType[] = [
  'adGroups',
  'ads',
  'automation',
  'bell',
  'bolt',
  'check-rounded-inverted',
  'check-rounded',
  'check',
  'chevron-right',
  'chevron',
  'close-big',
  'close-rounded',
  'close',
  'code',
  'creative',
  'data',
  'delete',
  'display',
  'dots',
  'download',
  'email-inverted',
  'email',
  'extend',
  'filters',
  'full-users',
  'file',
  'gears',
  'goals-rounded',
  'goals',
  'home',
  'image',
  'info',
  'laptop',
  'library',
  'magnifier',
  'menu-close',
  'minus',
  'optimization',
  'options',
  'partitions',
  'pause',
  'pen',
  'phone',
  'play',
  'plus',
  'query',
  'question',
  'refresh',
  'settings',
  'smartphone',
  'status',
  'tablet',
  'user',
  'users',
  'user-query',
  'user-pixel',
  'user-list',
  'video',
  'warning',
];

export default (
  <div style={{ maxWidth: '600px' }}>
    {typeList.map(type => (
      <McsIcon key={type} type={type} style={{ fontSize: '40px', margin: '8px' }} />
    ))}
  </div>
);
