import { PluginLayout } from '../../..';
import { PropertyResourceShape } from '../../../models/plugin';

export const mockReduxState = {
  features: {
    organisation: [
      'audience-segment_exports',
      'audience-segments',
      'audience-partitions',
      'audience-segment_builder',
      'audience-user_client_segment',
      'audience-monitoring',
      'campaigns-display',
      'campaigns-goals',
      'creatives-display',
      'creatives-email',
      'library-catalog',
      'library-assets',
      'library-zone',
      'datastudio-imports',
      'datastudio-query_tool',
      'datastudio-exports',
      'datastudio-report',
      'campaignsSettings-attribution_models',
      'campaignsSettings-email_routers',
      'campaignsSettings-recommenders',
      'organisationSettings-labels',
      'organisationSettings-users',
      'organisationSettings-settings',
      'datamartSettings-visit_analyzers',
      'datamartSettings-sites',
      'datamartSettings-mobile_applications',
      'datamartSettings-datamarts',
      'datamartSettings-service_usage_report',
      'accountSettings-profile',
      'accountSettings-api_tokens',
      'servicesSettings-subscribed_offers',
      'servicesSettings-my_offers',
      'audience-segment_builder-reference_table',
      'features-ui_feature_flag',
      'datamartSettings-mlAlgorithms',
      'datamartSettings-ml_function',
      'datamartSettings-audience_partitions',
      'audience-feeds',
      'plugins-presets',
      'datamartSettings-compartments',
      'datamartSettings-channels',
      null,
    ],
    client: {
      isBrowserClient: true,
    },
  },
  notifications: [],
  login: {
    hasError: false,
    error: {},
  },
  session: {
    workspace: {
      organisation_id: '1555185',
      customer_type: 'ENTERPRISE',
      organisation_name: 'FNAC-DARTY',
      administrator: false,
      role: 'READER',
      community_id: '155185',
      administrator_id: null,
      datamarts: [
        {
          id: '44545',
          name: 'Fnac-Darty',
          organisation_id: '1555185',
          token: 'fnacdarty17',
          creation_date: 5456456,
          time_zone: 'Europe/Paris',
          type: 'DATAMART',
          datafarm: 'DF_EU_2021_09',
          storage_model_version: 'v201555709',
          user_point_system_version: 'v20666709',
          region: 'EUROPE',
          archived: false,
          audience_segment_metrics: [],
        },
      ],
    },
    connectedUser: {
      id: '24656',
      first_name: 'John',
      last_name: 'do',
      email: 'jdo@mediarithmics.com',
      locale: null,
      workspaces: [
        {
          organisation_id: '1555185',
          customer_type: 'ENTERPRISE',
          organisation_name: 'FNAC-DARTY',
          administrator: false,
          role: 'READER',
          community_id: '1185',
          administrator_id: null,
          datamarts: [
            {
              id: '1156',
              name: 'Fnac-Darty',
              organisation_id: '1555185',
              token: 'fnacdarty17',
              creation_date: 1507113271992,
              time_zone: 'Europe/Paris',
              type: 'DATAMART',
              datafarm: 'DF_EU_2021_09',
              storage_model_version: 'v201570954',
              user_point_system_version: 'v20157049',
              region: 'EUROPE',
              archived: false,
              audience_segment_metrics: [],
            },
          ],
        },
      ],
      default_workspace: 12,
    },
    cookies: {
      mics_vid: '4145514',
      mics_lts: '45455545',
      mics_uaid: 'web:1:ca838b18-c5c354-431e-a5af-454455445',
    },
    connectedUserLoaded: true,
    isFechingCookies: false,
    isFetchingWorkspace: false,
    isUploadingLogo: false,
    logoUrl: 'https://navigator.mediarithmics.com/react/src/assets/images/logo.png',
  },
  labels: {
    labelsApi: {
      isFetching: false,
      data: [
        {
          id: '424',
          organisation_id: '1555185',
          name: 'FNAC',
          creation_ts: 15186518213394,
        },
      ],
      total: 11,
      status: 'ok',
      count: 11,
      first_result: 0,
      max_result: 21474583647,
      max_results: 21474583647,
    },
  },
};

export const mockPropertyResourceShapes: PropertyResourceShape[] = [
  {
    technical_name: 'fb_ad_account_id',
    value: { value: 'test' },
    property_type: 'STRING',
    origin: 'PLUGIN',
    writable: true,
    deletable: false,
  },
  {
    technical_name: 'fb_custom_audience_id',
    value: { value: '' },
    property_type: 'STRING',
    origin: 'PLUGIN',
    writable: true,
    deletable: false,
  },
  {
    technical_name: 'fb_custom_audience_name',
    value: { value: '' },
    property_type: 'STRING',
    origin: 'PLUGIN',
    writable: true,
    deletable: false,
  },
  {
    technical_name: 'fb_customer_file_source',
    value: { value: 'USER_PROVIDED_ONLY' },
    property_type: 'STRING',
    origin: 'PLUGIN',
    writable: true,
    deletable: false,
  },
  {
    technical_name: 'used_compartments',
    value: { value: '' },
    property_type: 'STRING',
    origin: 'PLUGIN',
    writable: true,
    deletable: false,
  },
  {
    technical_name: 'provider',
    value: { value: 'MEDIARITHMICS' },
    property_type: 'STRING',
    origin: 'PLUGIN_STATIC',
    writable: false,
    deletable: false,
  },
  {
    technical_name: 'name',
    value: { value: 'Facebook Custom Audience (based on CRM data)' },
    property_type: 'STRING',
    origin: 'PLUGIN_STATIC',
    writable: false,
    deletable: false,
  },
];

export const mockPluginLayout: PluginLayout = {
  version: 'V201801',
  sections: [
    {
      title: 'Facebook Custom Audience',
      sub_title: 'Synchronize your CRM Audiences with Facebook',
      fields: [
        {
          property_technical_name: 'fb_ad_account_id',
          field_type: 'INPUT',
          label: 'Facebook Ad Account ID',
          tooltip:
            'The ID of the Facebook Ad Account to which you want to synchronize your audience.',
          required: true,
        },
        {
          property_technical_name: 'used_compartments',
          field_type: 'INPUT',
          label: 'Compartments to use',
          tooltip:
            'The compartment(s) from which the CRM data will be used. Format (case 1): 1111. Format (case 2): 1111,2222,3333. If you need to send mobile Ids you could add MOBILE, MOBILE_AND or MOBILE_IOS to the list of compartments to use. Format (case 3): 1111,2222,MOBILE_AND.',
          required: false,
        },
        {
          property_technical_name: 'fb_customer_file_source',
          field_type: 'SELECT',
          label: 'Customer file source',
          tooltip:
            'Describes how the customer information in your Custom Audience was originally collected. USER_PROVIDED_ONLY: Advertisers collected information directly from customers. PARTNER_PROVIDED_ONLY: Advertisers sourced information directly from partners (e.g. agencies or data providers). BOTH_USER_AND_PARTNER_ PROVIDED: Advertisers collected information directly from customers and it was also sourced from partners (ex: agencies).',
          enum: [
            { value: 'USER_PROVIDED_ONLY', label: 'USER PROVIDED ONLY (FIRST PARTY)' },
            { value: 'PARTNER_PROVIDED_ONLY', label: 'PARTNER PROVIDED ONLY (THIRD PARTY)' },
            { value: 'BOTH_USER_AND_PARTNER_PROVIDED', label: 'BOTH USER AND PARTNER PROVIDED' },
          ],
          required: true,
        },
      ],
      advanced_fields: [
        {
          property_technical_name: 'fb_custom_audience_id',
          field_type: 'INPUT',
          label: 'Facebook Custom Audience ID',
          tooltip:
            'If you want to enrich an existing Facebook Custom Audience, you can retrieve it by specifiying its ID here',
        },
        {
          property_technical_name: 'fb_custom_audience_name',
          field_type: 'INPUT',
          label: 'Facebook Custom Audience name',
          tooltip:
            'If you want to use a specific name for your Custom Audience, specify it here. Default name is the same as your segment in mediarithmics DMP',
        },
      ],
    },
  ],
  metadata: {
    large_icon_asset_id: '9656',
    small_icon_asset_id: '9656',
    large_icon_asset_url: '/1/public/assets/1543859195254-NaPcgfuo/flogo_RGB_HEX-512.svg',
    small_icon_asset_url: '/1/public/assets/1543859195254-NaPcgfuo/flogo_RGB_HEX-512.svg',
    display_name: 'Facebook Custom Audience',
    description: 'Synchronize your CRM Audiences with Facebook',
  },
};
